# Generated by Django 2.2.6 on 2019-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id_kota', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kota', models.CharField(max_length=50)),
            ],
        ),
    ]
