# Generated by Django 2.2.6 on 2019-11-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_kuliner',
            fields=[
                ('id_kk', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kuliner',
            fields=[
                ('id_kuliner', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('jam_buka', models.TimeField()),
                ('jam_tutup', models.TimeField()),
                ('alamat', models.CharField(max_length=250)),
                ('deskripsi', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pon.Kategori_kuliner')),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pon.Kota')),
            ],
        ),
    ]
