# Generated by Django 2.2.6 on 2019-11-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0003_auto_20191126_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_kuliner',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
