# Generated by Django 2.2.6 on 2019-11-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0004_auto_20191126_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_kuliner',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
