# Generated by Django 2.2.6 on 2019-11-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0005_item_kuliner_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_penginapan',
            fields=[
                ('id_kp', models.AutoField(primary_key=True, serialize=False)),
                ('kp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penginapan',
            fields=[
                ('id_penginapan', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
                ('alamat', models.CharField(max_length=250)),
                ('deskripsi', models.TextField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pon.Kategori_penginapan')),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pon.Kota')),
            ],
        ),
    ]
