# Generated by Django 2.2.6 on 2019-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0006_kategori_penginapan_penginapan'),
    ]

    operations = [
        migrations.AddField(
            model_name='penginapan',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
