# Generated by Django 2.2.6 on 2019-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pon', '0007_penginapan_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id_fasilitas', models.AutoField(primary_key=True, serialize=False)),
                ('item_fasilitas', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kategori_penginapan',
            options={'ordering': ('id_kp',)},
        ),
        migrations.AlterModelOptions(
            name='penginapan',
            options={'ordering': ('id_penginapan',)},
        ),
        migrations.CreateModel(
            name='ItemKamar',
            fields=[
                ('id_kamar', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=150)),
                ('type_ranjang', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('fasilitas', models.ManyToManyField(to='pon.Fasilitas')),
                ('penginapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pon.Penginapan')),
            ],
            options={
                'ordering': ('id_kamar',),
            },
        ),
    ]
